# 系统配置
server:
  port: 8086
  tomcat:
    uri-encoding: utf-8
debug: true
logging:
  level:
    # 增加mybatis日志打印sql
    com.qiushengming.mapper: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file: log\springboot.log

# spring配置
spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates
  activemq:
    broker-url: tcp://192.168.16.113:61616
    user: admin
    password: admin
    pool:
      enabled: false
  jms:
    pub-sub-domain: true
  profiles:
      active: dev
  datasource:
#      url: jdbc:oracle:thin:@192.168.16.113:1521:sunshine # jdbc:mysql://localhost:3306/sunshine?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: luun
#      password: luun # 192.168.16.113-123；localhost-minnie
#      driver-class-name: oracle.jdbc.driver.OracleDriver # com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.16.113:3306/sunshine?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123
      platform: mysql
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x' FROM dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  redis:
    database: 1
    host: 192.168.5.94 # 192.68.5.94
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负数表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中最大空闲链接
        min-idle: 0 # 连接池中最小空闲链接
    # 连接超时时间（毫秒数）
    timeout: 5000

mybatis:
    mapper-locations: classpath*:mapper/*.xml
    typeAliasesPackage: com.qiushengming.entity
minnie:
  mybatis:
    basePackage: com.qiushengming.mapper
  druid:
    loginUserName: admin1
    loginPassword: admin1
    allow: 192.168.16.118,192.168.16.113
    deny: 192.168.16.110

