-- 药物成分表
CREATE TABLE QSM_DRUG_INGREDIENT AS
  SELECT
    SYS_GUID()       ID,
    BIG_GENERIC_NAME INGREDIENT,
    PINYIN_CODE,
    DRUG_TYPE INGREDIENT_TYPE
  FROM KBMS_DRUG_BIG_GENERIC;
COMMENT ON TABLE QSM_DRUG_INGREDIENT IS '药物成分表';
COMMENT ON COLUMN QSM_DRUG_INGREDIENT.INGREDIENT IS '药物成分名称';
COMMENT ON COLUMN QSM_DRUG_INGREDIENT.INGREDIENT_TYPE IS '药物成分类型，1-中成药 or 2-西药';
COMMENT ON COLUMN QSM_DRUG_INGREDIENT.PINYIN_CODE IS '药物成分名称拼音首字母';



