CREATE TABLE GRID_VIEW_CONFIGURE (
  ID                 VARCHAR(255) PRIMARY KEY NOT NULL,
  MODULE_NAME        VARCHAR(255) UNIQUE      NOT NULL,
  URL                VARCHAR(125) UNIQUE      NOT NULL,
  PAGE_SIZE          SMALLINT     DEFAULT 25,
  SORTERS            VARCHAR(255) DEFAULT 'ID#ASC',
  FORCE_FIT          TINYINT(1)   DEFAULT 1,
  AUTO_SCROLL        TINYINT(1)   DEFAULT 1,
  ROW_LINES          TINYINT(1)   DEFAULT 1,
  COLUMN_LINES       TINYINT(1)   DEFAULT 1,
  ENABLE_COLUMN_HIDE TINYINT(1)   DEFAULT 1,
  START_LOAD TINYINT(1)   DEFAULT 1
);
INSERT INTO grid_view_configure (ID, MODULE_NAME, URL) VALUES ('1', 'Book', '/getBooks');

CREATE TABLE EXT_COULUMN (
  ID         VARCHAR(36) PRIMARY KEY,
  MODULE_ID  VARCHAR(255)              NOT NULL,
  HEADER     VARCHAR(255) DEFAULT '默认' NOT NULL,
  DATA_INDEX VARCHAR(255)              NOT NULL,
  SEALED     TINYINT(1)                NOT NULL DEFAULT 0,
  HIDDEN     TINYINT(1)                NOT NULL DEFAULT 0,
  HIDEABLE   TINYINT(1)                NOT NULL DEFAULT 1,
  SORTABLE   TINYINT(1)                NOT NULL DEFAULT 1,
  GROUPABLE  TINYINT(1)                NOT NULL DEFAULT 1,
  WIDTH      SMALLINT                  NOT NULL DEFAULT 125
);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, HEADER, DATA_INDEX, HIDDEN, HIDEABLE)
VALUES (REPLACE(UUID(), '-', ''), '1', 'ID', 'id', 1, 0);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, HEADER, DATA_INDEX, GROUPABLE)
VALUES (REPLACE(UUID(), '-', ''), '1', '书名', 'name', 0);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, HEADER, DATA_INDEX, GROUPABLE)
VALUES (REPLACE(UUID(), '-', ''), '1', '作者', 'author', 0);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, HEADER, DATA_INDEX, GROUPABLE)
VALUES (REPLACE(UUID(), '-', ''), '1', '归属', 'affiliation', 0);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, HEADER, DATA_INDEX)
VALUES (REPLACE(UUID(), '-', ''), '1', '占用', 'occupy');

SELECT *
FROM GRID_VIEW_CONFIGURE;
SELECT *
FROM EXT_COULUMN;
SELECT * FROM book;

DELETE FROM EXT_COULUMN;

DROP TABLE EXT_COULUMN;
