CREATE TABLE GRID_VIEW_CONFIGURE (
  ID                 VARCHAR(255) PRIMARY KEY NOT NULL,
  MODULE_NAME        VARCHAR(255) UNIQUE      NOT NULL,
  URL                VARCHAR(125) UNIQUE      NOT NULL,
  PAGE_SIZE          SMALLINT     DEFAULT 25,
  SORTERS            VARCHAR(255) DEFAULT 'ID#ASC',
  FORCE_FIT          TINYINT(1)   DEFAULT 1,
  AUTO_SCROLL        TINYINT(1)   DEFAULT 1,
  ROW_LINES          TINYINT(1)   DEFAULT 1,
  COLUMN_LINES       TINYINT(1)   DEFAULT 1,
  ENABLE_COLUMN_HIDE TINYINT(1)   DEFAULT 1,
  START_LOAD         TINYINT(1)   DEFAULT 1
);
INSERT INTO grid_view_configure (ID, MODULE_NAME, URL)
VALUES ('1', 'Book', '/getBooks');

CREATE TABLE EXT_COULUMN (
  ID         VARCHAR(36) PRIMARY KEY,
  MODULE_ID  VARCHAR(255)              NOT NULL,
  HEADER     VARCHAR(255) DEFAULT '默认' NOT NULL,
  DATA_INDEX VARCHAR(255)              NOT NULL,
  SEALED     TINYINT(1)                NOT NULL DEFAULT 0,
  HIDDEN     TINYINT(1)                NOT NULL DEFAULT 0,
  HIDEABLE   TINYINT(1)                NOT NULL DEFAULT 1,
  SORTABLE   TINYINT(1)                NOT NULL DEFAULT 1,
  GROUPABLE  TINYINT(1)                NOT NULL DEFAULT 1,
  WIDTH      SMALLINT                  NOT NULL DEFAULT 125
);
ALTER TABLE EXT_COULUMN
  ADD (EDITOR VARCHAR(500) DEFAULT '{"xtype": "textfield"}');
ALTER TABLE EXT_COULUMN
  ADD (ORDER_INDEX TINYINT(5) DEFAULT 0);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, ORDER_INDEX, HEADER, DATA_INDEX, HIDDEN, HIDEABLE)
VALUES (REPLACE(UUID(), '-', ''), '1', 0, 'ID', 'id', 1, 0);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, ORDER_INDEX, HEADER, DATA_INDEX, GROUPABLE)
VALUES (REPLACE(UUID(), '-', ''), '1', 2, '书名', 'name', 0);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, ORDER_INDEX, HEADER, DATA_INDEX, GROUPABLE)
VALUES (REPLACE(UUID(), '-', ''), '1', 3, '作者', 'author', 0);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, ORDER_INDEX, HEADER, DATA_INDEX, GROUPABLE)
VALUES (REPLACE(UUID(), '-', ''), '1', 4, '归属', 'affiliation', 0);
INSERT INTO EXT_COULUMN (ID, MODULE_ID, ORDER_INDEX, HEADER, DATA_INDEX, EDITOR)
VALUES (REPLACE(UUID(), '-', ''), '1', 5, '占用', 'occupy', '{"xtype": "uxcombobox"}');
INSERT INTO EXT_COULUMN (ID, MODULE_ID, ORDER_INDEX, HEADER, DATA_INDEX, EDITOR)
VALUES (REPLACE(UUID(), '-', ''), '1', 6, '测试', 'occupy', '{"xtype": "textfield", "allowBlank": false}');

-- 插件配置信息
CREATE TABLE EXT_PLUGIN (
  ID        VARCHAR(36) PRIMARY KEY,
  MODULE_ID VARCHAR(36) NOT NULL,
  PTYPE     VARCHAR(36) NOT NULL,
  CONFIG    VARCHAR(2000)
);
INSERT INTO EXT_PLUGIN (ID, MODULE_ID, PTYPE, CONFIG)
VALUES (REPLACE(UUID(), '-', ''), '1', 'rowediting', '{"clicksToEdit": 5}');

-- 字典
CREATE TABLE DICTIONARY (
  ID         VARCHAR(36) PRIMARY KEY,
  VALUE      VARCHAR(36) NOT NULL,
  NAME       VARCHAR(36) NOT NULL,
  REMARK     VARCHAR(255),
  TYPE_CODE  VARCHAR(36),
  VIEW_ORDER TINYINT(5) DEFAULT 0
);
INSERT INTO dictionary (ID, VALUE, NAME, REMARK, TYPE_CODE, VIEW_ORDER)
VALUES ('1ed2343eb6cb10369c96c62771c06ee8', '1', '仓库', NULL, 'TYPE', 0);
INSERT INTO dictionary (ID, VALUE, NAME, REMARK, TYPE_CODE, VIEW_ORDER)
VALUES ('3ae87123b6cb10369c96c62771c06ee8', '2', '出借', NULL, 'TYPE', 1);

